# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kotlin: # Kotlin and KSP
        patterns:
          - "org.jetbrains.kotlin:*"
          - "com.google.devtools.ksp"
      agp: # APG and SVG to xml convertor
        patterns:
          - "com.android.*"
          - "com.android.tools:sdk-common"
    commit-message:
      prefix: "build"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "pip"
    directories:
      - "/script/icons"
      - "/script/blurhash"
      - "/script/crowdin"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
