project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"

files:
  - source: "/app/src/main/res/values/strings.xml"
    translation: "/app/src/main/res/values-%android_code%/%original_file_name%"
    update_option: update_as_unapproved
    skip_untranslated_files: true
    # https://developer.crowdin.com/language-codes/
    languages_mapping:
      android_code:
        zh-CN: "zh"
        ru-RU: "ru"
        it-IT: "it"
        es-ES: "es"
        fr-FR: "fr"
        pt-PT: "pt"
        de-DE: "de"

  - source: "/app/src/main/res/values/languages.xml"
    translation: "/app/src/main/res/values-%android_code%/%original_file_name%"
    skip_untranslated_files: true
    languages_mapping:
      android_code:
        zh-CN: "zh"
        ru-RU: "ru"
        it-IT: "it"
        es-ES: "es"
        fr-FR: "fr"
        pt-PT: "pt"
        de-DE: "de"
